# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00eb4da1e12c6477ee052667074d75c833d0c9e6ff0d1ff5d027276489601dd9e4ae7232e2887f2038b1596cd75a51f3583569d9f4a76a8033f3e70eb344c873

test:
  secret_key_base: 3a1125a1626daba6224ce96797409c1cebc526815a1693f3ce08423d6491a2d97bcd611c0f451a694e8a53dc3dd270562780cac80b88dbfeb071a8e1ac5b4b64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
